# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=2.0.0
group=com.kekecreations.configurable_falls

# Common
minecraft_version=1.20.2
mod_name=Configurable Falls
mod_author=KekeCreations
mod_id=configurable_falls
license=All Rights Reserved
credits=A special thanks to @ArBeeeet for making the mod icon and the mod banner!
description=This mod adds many configurable features that are related to falling and fall damage in Minecraft.
minecraft_version_range=[1.20.2, 1.21)

# Fabric
fabric_version=0.91.0+1.20.2
fabric_loader_version=0.15.0

# Forge
forge_version=48.0.49
forge_loader_version_range=[48,)
forge_version_range=[48,)

# NeoForge
neoforge_version=20.2.86
neoforge_loader_version_range=[1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
